import type { Metadata } from 'next';
import {
  Ruthie,
  Saira_Semi_Condensed,
  Saira_Condensed,
  Lora,
} from 'next/font/google';
import './globals.css';

const serifFont = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
  fallback: ['serif'],
});
const sansFont = Saira_Semi_Condensed({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
  weight: ['300', '700'],
  fallback: ['sans-serif'],
});
const condensedFont = Saira_Condensed({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-condensed',
  weight: ['300', '700'],
  fallback: ['sans-serif'],
});
const scriptFont = Ruthie({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-script',
  fallback: ['cursive'],
});

const className = [serifFont, sansFont, condensedFont, scriptFont]
  .map((f) => f.variable)
  .join(' ');

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout<FC>({
  children,
  ...rest
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-GB" className={className}>
      {children}
    </html>
  );
}
