import type { Metadata } from 'next';
import { Lora, Euphoria_Script, Source_Sans_3 } from 'next/font/google';
import './globals.css';

const serifFont = Lora({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
  fallback: ['serif'],
});
const sansFont = Source_Sans_3({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
  fallback: ['sans-serif'],
});
const scriptFont = Euphoria_Script({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-script',
  fallback: ['cursive'],
});

const className = [serifFont, sansFont, scriptFont]
  .map((f) => f.variable)
  .join(' ');

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout<FC>({
  children,
  ...rest
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en-GB" className={className}>
      {children}
    </html>
  );
}
